-- MySQL Script generated by MySQL Workbench
-- dom 28 abr 2019 20:07:40 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb	
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Inventario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `idInventario` INT NOT NULL,
  `cantidadProducto` VARCHAR(45) NULL,
  PRIMARY KEY (`idInventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Restaurante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Restaurante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Restaurante` (
  `idRestaurante` INT NOT NULL AUTO_INCREMENT,
  `nombreRestaurante` VARCHAR(45) NOT NULL,
  `ubicacion` VARCHAR(45) NOT NULL,
  `nit` VARCHAR(45) NOT NULL,
  `numeroContacto` VARCHAR(13) NOT NULL,
  `correoContacto` VARCHAR(45) NULL,
  `Inventario_idInventario` INT NOT NULL,
  `cantidadMesas` INT NOT NULL,
  `regimen` INT NOT NULL,
  PRIMARY KEY (`idRestaurante`),
  INDEX `fk_Empresa_Inventario1_idx` (`Inventario_idInventario` ASC) ,
  CONSTRAINT `fk_Empresa_Inventario1`
    FOREIGN KEY (`Inventario_idInventario`)
    REFERENCES `mydb`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nomina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Nomina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Nomina` (
  `idNomina` INT NOT NULL AUTO_INCREMENT,
  `arl` INT NULL,
  `eps` INT NULL,
  `pension` INT NULL,
  `parafiscal` INT NULL,
  `cesantia` INT NULL,
  `otrosGatos` INT NULL,
  PRIMARY KEY (`idNomina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombreEmpleado` VARCHAR(45) NOT NULL,
  `telEmpleados` VARCHAR(45) NOT NULL,
  `correoEmpleado` VARCHAR(45) NULL,
  `SalarioEmpleado` INT UNSIGNED NOT NULL,
  `Restaurante_idRestaurante` INT NOT NULL,
  `Nomina_idNomina` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_Empleado_Restaurante1_idx` (`Restaurante_idRestaurante` ASC) ,
  INDEX `fk_Empleado_Nomina1_idx` (`Nomina_idNomina` ASC) ,
  CONSTRAINT `fk_Empleado_Restaurante1`
    FOREIGN KEY (`Restaurante_idRestaurante`)
    REFERENCES `mydb`.`Restaurante` (`idRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleado_Nomina1`
    FOREIGN KEY (`Nomina_idNomina`)
    REFERENCES `mydb`.`Nomina` (`idNomina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MedidasProducto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MedidasProducto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MedidasProducto` (
  `idMedidasProducto` INT NOT NULL AUTO_INCREMENT,
  `MedidasProductocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMedidasProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL ,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `marcaProducto` VARCHAR(45) NOT NULL,
  `fechaVencimiento` VARCHAR(45) NOT NULL,
  `Costo` INT NULL,
  `MedidasProducto_idMedidasProducto` INT NOT NULL,
  `MedidasProducto_idMedidasProducto1` INT NOT NULL,
  PRIMARY KEY (`nombreProducto`, `MedidasProducto_idMedidasProducto`),
  INDEX `fk_Producto_MedidasProducto1_idx` (`MedidasProducto_idMedidasProducto1` ASC) ,
  CONSTRAINT `fk_Producto_MedidasProducto1`
    FOREIGN KEY (`MedidasProducto_idMedidasProducto1`)
    REFERENCES `mydb`.`MedidasProducto` (`idMedidasProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_has_Inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto_has_Inventario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producto_has_Inventario` (
  `Producto_nombreProducto` VARCHAR(45) NOT NULL,
  `Inventario_idInventario` INT NOT NULL,
  PRIMARY KEY (`Producto_nombreProducto`, `Inventario_idInventario`),
  INDEX `fk_Producto_has_Inventario_Inventario1_idx` (`Inventario_idInventario` ASC) ,
  INDEX `fk_Producto_has_Inventario_Producto1_idx` (`Producto_nombreProducto` ASC) ,
  CONSTRAINT `fk_Producto_has_Inventario_Producto1`
    FOREIGN KEY (`Producto_nombreProducto`)
    REFERENCES `mydb`.`Producto` (`nombreProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Inventario_Inventario1`
    FOREIGN KEY (`Inventario_idInventario`)
    REFERENCES `mydb`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `telUsuario` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `correoUsuario` VARCHAR(45) NOT NULL,
  `Restaurante_idRestaurante` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Restaurante1_idx` (`Restaurante_idRestaurante` ASC) ,
  CONSTRAINT `fk_Usuario_Restaurante1`
    FOREIGN KEY (`Restaurante_idRestaurante`)
    REFERENCES `mydb`.`Restaurante` (`idRestaurante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Platos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Platos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Platos` (
  `idPlatos` INT NOT NULL AUTO_INCREMENT,
  `nombrePlato` VARCHAR(45) NULL,
  `PrecioPlato` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlatos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Platos_has_Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Platos_has_Producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Platos_has_Producto` (
  `Platos_idPlatos` INT NOT NULL,
  `Producto_nombreProducto` VARCHAR(45) NOT NULL,
  `Producto_MedidasProducto_idMedidasProducto` INT NOT NULL,
  `cantidadPlatoProducto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Platos_idPlatos`, `Producto_nombreProducto`, `Producto_MedidasProducto_idMedidasProducto`),
  INDEX `fk_Platos_has_Producto_Producto1_idx` (`Producto_nombreProducto` ASC, `Producto_MedidasProducto_idMedidasProducto` ASC) ,
  INDEX `fk_Platos_has_Producto_Platos1_idx` (`Platos_idPlatos` ASC) ,
  CONSTRAINT `fk_Platos_has_Producto_Platos1`
    FOREIGN KEY (`Platos_idPlatos`)
    REFERENCES `mydb`.`Platos` (`idPlatos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Platos_has_Producto_Producto1`
    FOREIGN KEY (`Producto_nombreProducto` , `Producto_MedidasProducto_idMedidasProducto`)
    REFERENCES `mydb`.`Producto` (`nombreProducto` , `MedidasProducto_idMedidasProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mesa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mesa` (
  `idMesa` INT NOT NULL AUTO_INCREMENT,
  `capacidad` INT NOT NULL,
  `disponibilidad` TINYINT NOT NULL,
  PRIMARY KEY (`idMesa`))
ENGINE = InnoDB;
insert into Mesa values(1,4,0);
insert into Mesa values(2,2,0);
insert into Mesa values(3,3,1);
select * from Mesa;

-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `horaFechaLlegada` TIMESTAMP NOT NULL,
  `costoPedido` INT NOT NULL,
  `Mesa_idMesa` INT NOT NULL,
  `Empleado_idEmpleado` INT NOT NULL,
  `estado` VARCHAR(10) NOT NULL,
  `horaFechaSalida` DATE NOT NULL,
  `propina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPedido`, `Empleado_idEmpleado`),
  INDEX `fk_Pedido_Mesa1_idx` (`Mesa_idMesa` ASC) ,
  INDEX `fk_Pedido_Empleado1_idx` (`Empleado_idEmpleado` ASC) ,
  CONSTRAINT `fk_Pedido_Mesa1`
    FOREIGN KEY (`Mesa_idMesa`)
    REFERENCES `mydb`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Empleado1`
    FOREIGN KEY (`Empleado_idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Platos_has_Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Platos_has_Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Platos_has_Pedido` (
  `Platos_idPlatos` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  PRIMARY KEY (`Platos_idPlatos`, `Pedido_idPedido`),
  INDEX `fk_Platos_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) ,
  INDEX `fk_Platos_has_Pedido_Platos1_idx` (`Platos_idPlatos` ASC) ,
  CONSTRAINT `fk_Platos_has_Pedido_Platos1`
    FOREIGN KEY (`Platos_idPlatos`)
    REFERENCES `mydb`.`Platos` (`idPlatos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Platos_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reserva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reserva` (
  `idReserva` INT NOT NULL AUTO_INCREMENT,
  `nombreCliente` VARCHAR(45) NOT NULL,
  `telCliente` VARCHAR(45) NOT NULL,
  `correoCliente` VARCHAR(45) NOT NULL,
  `tipoCelebracion` VARCHAR(45) NOT NULL,
  `HoraFecha` TIMESTAMP NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `paqueteElegido` VARCHAR(45) NOT NULL,
  `Mesa_idMesa` INT NOT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_Reserva_Mesa1_idx` (`Mesa_idMesa` ASC) ,
  CONSTRAINT `fk_Reserva_Mesa1`
    FOREIGN KEY (`Mesa_idMesa`)
    REFERENCES `mydb`.`Mesa` (`idMesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
insert into Reserva values(1,'ricardo','314','hola@hola.com','cumpleaños','22/33/23:23:56','','1','3');
select * from Reserva;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use mydb;
select * from Restaurante;
insert into Inventario values(1,36);
insert into Restaurante values(1,'meandros','girardota',123,'312','me@me',1,25,2);
insert into Usuario values(1,'admin',)